# Assignment 1

### FDP1

In [1]:
import numpy as np
import numpy.matlib as mb
import random
import math

In [2]:
A=np.array([[0.8,0.1,0.1],[0.2,0.6,0.2],[0.1,0.2,0.7]])
print(A)
m,n=np.shape(A)
A=np.transpose(A)
Ainf=np.power(A,50)
e1=Ainf[:,0]

[[0.8 0.1 0.1]
 [0.2 0.6 0.2]
 [0.1 0.2 0.7]]


In [3]:
print('A*first column of Ainf')
print(A*e1)

A*first column of Ainf
[[1.14179815e-05 2.00000000e-51 1.00000000e-51]
 [1.42724769e-06 6.00000000e-51 2.00000000e-51]
 [1.42724769e-06 2.00000000e-51 7.00000000e-51]]


In [4]:
eigval,eigvec=np.linalg.eig(A)
column_sum=sum(abs(eigvec))
divisor=mb.repmat(column_sum,m,1)
sumnorm_eigvec=np.divide(eigvec,divisor)
print('All sum_normalized eigen vector of A')
print(sumnorm_eigvec)
print('All eigen values of A')
print(np.diag(eigval))

All sum_normalized eigen vector of A
[[-0.42105263 -0.5         0.19098301]
 [-0.26315789  0.19098301 -0.5       ]
 [-0.31578947  0.30901699  0.30901699]]
All eigen values of A
[[1.        0.        0.       ]
 [0.        0.6618034 0.       ]
 [0.        0.        0.4381966]]


### FDP2

In [5]:
T=np.array([[0.8,0.1,0.1],[0.2,0.6,0.2],[0.15,0.15,0.7]])
n=1000
s=np.empty([n])
s[0]=random.randint(1,3)

In [6]:
for i in range(n-1):
    cs=s[i] 
    if cs==1:
        r=random.random()
        if r<T[0,0]:
            s[i+1]=1
        elif  r<T[0,0]+T[0,1]:
            s[i+1]=2
        else:
            s[i+1]=3
    elif cs==2:
        r=random.random()
        if r<T[1,0]:
            s[i+1]=1
        elif r<T[1,0]+T[1,1]:
            s[i+1]=2
        else:
            s[i+1]=3;
    else:
        r=random.random()
        if r<T[2,0]:
            s[i+1]=1;
        elif  r<T[2,0]+T[2,1]:
            s[i+1]=2
        else:
            s[i+1]=3

print('Part of state sequence')
print(s[np.arange(0,12)])

Part of state sequence
[3. 3. 3. 3. 3. 3. 3. 2. 2. 1. 1. 2.]


In [7]:
# Counting transition
A=np.zeros((3,3))
n=np.size(s)
for i in range(n-1):
    k=int(s[i])
    l=int(s[i+1])
    A[k-1,l-1]=A[k-1,l-1]+1
print('Estimated transition probabilities')
rowsum=np.transpose(np.array([sum(A,2)]));
div=mb.repmat(rowsum,1,3);
A=np.divide(A,div)
print(A)
print('Original transition probabilities')
print(T)

Estimated transition probabilities
[[0.80284553 0.09756098 0.09349593]
 [0.22641509 0.52830189 0.23584906]
 [0.15614618 0.16611296 0.6744186 ]]
Original transition probabilities
[[0.8  0.1  0.1 ]
 [0.2  0.6  0.2 ]
 [0.15 0.15 0.7 ]]


### FDP 3

In [8]:
#HMM data Generation
# transition prob are [T11 T12; T21 T22]
T=np.array([[0.5,0.5],[0.4,0.6]])
state1h=0.7
state1t=0.3
state2h=0.6
state2t=0.4
x=random.random()
if x<0.5:
    start_state=1;
else:
    start_state=2;

current_state=start_state;

s=np.empty([100000])
s[0]=current_state
Obs=''
for i in range(1,100000):
    if current_state==1:
        x=random.random()
        if x<state1h:
            Obs+='H';
        else:
            Obs+='T';
        x=random.random();
        if x<T[0,0]:
            current_state=1;
        else:
            current_state=2; 
    else:
        x=random.random()
        if x<state2h:
            Obs+='H'
        else:
            Obs+='T'
        x=random.random();
        if x<T[1,1]:
            current_state=2;
        else:
            current_state=1; 
    s[i]=current_state;

In [9]:
#Obs;
s=s[np.arange(np.size(s)-1)]
stat1CH=0;
stat1CT=0;
stat2CH=0;
stat2CT=0;
Obs=np.array(list(Obs))
for i in range(np.size(s)):
    e=Obs[i];
    if s[i]==1 and e=='H':
        stat1CH=stat1CH+1
    elif s[i]==1 and e=='T':
        stat1CT=stat1CT+1  
    elif s[i]==2 and e=='H':
        stat2CH=stat2CH+1;
    else:
        stat2CT=stat2CT+1;

print('part of state sequence')
print(s[np.arange(10)]);
print('part of symbol sequence')
print(Obs[np.arange(10)]);
total=stat1CH+stat1CT+stat2CH+stat2CT
e1H=stat1CH/(stat1CH+stat1CT);
e1T=stat1CT/(stat1CH+stat1CT);
e2H=stat2CH/(stat2CH+stat2CT);
e2T=stat2CT/(stat2CH+stat2CT);
print('restimated emission probabilities')
print('e1(H)')
print(e1H)
print('e1(T)')
print(e1T)
print('e2(H)')
print(e2H)
print('e2(T)')
print(e2T)

part of state sequence
[1. 2. 1. 2. 2. 2. 1. 2. 2. 2.]
part of symbol sequence
['H' 'H' 'H' 'H' 'H' 'T' 'T' 'H' 'H' 'H']
restimated emission probabilities
e1(H)
0.7017654334870123
e1(T)
0.29823456651298774
e2(H)
0.6014333561421832
e2(T)
0.3985666438578168


### FDP 4

In [10]:
def ibase(n, radix=2, maxlen=None):
    r = []
    while n:
        n,p = divmod(n, radix)
        r.append('%d' % p)
        if maxlen and len(r) > maxlen:
            break
    r.reverse()
    if len(r)<maxlen:
        for i in range(maxlen-len(r)):
            r.insert(0,'0')
    return ''.join(r)

In [11]:
n=32;
Seq=np.array(['22222']);
for i in range(1,n):
    x=ibase(i,2,5)
    x= x.replace('0','2')
    Seq=np.append(Seq,x)
Seq

array(['22222', '22221', '22212', '22211', '22122', '22121', '22112',
       '22111', '21222', '21221', '21212', '21211', '21122', '21121',
       '21112', '21111', '12222', '12221', '12212', '12211', '12122',
       '12121', '12112', '12111', '11222', '11221', '11212', '11211',
       '11122', '11121', '11112', '11111'], dtype='<U5')

### FDP 5

In [12]:
# Find  P(sym_sequence,satae_sequence)
# It is joint probability
# Let us take T's elements as [ T11 T12 ; T21 T22[
# actual transition prob is transpose of T
T=np.array([[0.5,0.5],[0.4,0.6]]);
state1h=0.7
state1t=0.3
state2h=0.6
state2t=0.4
x='HTTTH'

n=len(x); # length of symbol sequence
N=2**5;

# Get sym_sequence probabiity
prodx=1;
stat_seq=Seq[9]; # take 10th row
for i in range(len(x)):
    if stat_seq[i]==1:
        if x[i]=='H':
            rodx=prodx*state1h;
        else:
            prodx=prodx*state1t;  
    else:
        if x[i]=='H':
            prodx=prodx*state2h;
        else:
            prodx=prodx*state2t;  
            
#Get trans_sequence probabiity
prods=1;
for i in range(n-1):
    j=int(stat_seq[i]);
    k=int(stat_seq[i+1]);
    prods=prods*T[j-1,k-1];

reqd_prob=prodx*prods
reqd_prob

0.00110592

### FDP 6

In [23]:
# Forward Probability tabke Generation
T=np.array([[0.7,0.3],[0.2,0.8]])
state1H=0.8 
state1T=0.2
state2H=0.3  
state2T=0.7
Sequence='HTTH'
Sequence=np.array(list(Sequence))
s1Prob=np.empty([n])
s2Prob=np.empty([n])
L=len(Sequence)
# Dummy prob array  for fast computation
for i in range(L): 
    if Sequence[i]=='H':
        s1Prob[i]=state1H;
        s2Prob[i]=state2H;
    else:
        s1Prob[i]=state1T;
        s2Prob[i]=state2T; 

ForwardT=np.zeros((2,L));
ForwardT[0,0]=0.5*s1Prob[0];
ForwardT[1,0]=0.5*s2Prob[0];

for j in range(1,L):
    ForwardT[0,j]=ForwardT[0,j-1]*T[0,0]*s1Prob[j]+ForwardT[1,j-1]*T[1,0]*s1Prob[j];
    ForwardT[1,j]=ForwardT[0,j-1]*T[0,1]*s2Prob[j]+ForwardT[1,j-1]*T[1,1]*s2Prob[j];

print('Observed Sequence is')
print(Sequence)

ForwardT

prob_of_sequence=sum(ForwardT[:,L-1]);

print("\n",'prob_of_sequence=',prob_of_sequence)

Observed Sequence is
['H' 'T' 'T' 'H']

 prob_of_sequence= 0.052849999999999994


### FDP 7

In [28]:
# Backward Algorithm
#HMM data Generation
T=np.array([[0.7,0.3],[0.2,0.8]])
state1H=0.8 
state1T=0.2
state2H=0.3  
state2T=0.7
Sequence='HTTH'
Sequence=np.array(list(Sequence))
s1Prob=np.empty([n])
s2Prob=np.empty([n])
L=len(Sequence)
# Dummy prob array  for fast computation
for i in range(L): 
    if Sequence[i]=='H':
        s1Prob[i]=state1H;
        s2Prob[i]=state2H;
    else:
        s1Prob[i]=state1T;
        s2Prob[i]=state2T; 

BackwardT=np.zeros((2,L));
BackwardT[0,L-1]=1;
BackwardT[1,L-1]=1;
for i in reversed(range(0,L-1,1)):
    BackwardT[0,i]= T[0,0]* s1Prob[i+1]*BackwardT[0,i+1] + T[0,1]*s2Prob[i+1]*BackwardT[1,i+1];
    BackwardT[1,i]= T[1,0]* s1Prob[i+1]*BackwardT[0,i+1] + T[1,1]*s2Prob[i+1]*BackwardT[1,i+1];


print('backward Probability Table')
print(BackwardT)

print("\n",'Probabiliy of sequence=')
prob_seqx=0.5*BackwardT[0,0]*s1Prob[0]+0.5*BackwardT[1,0]*s2Prob[0]
print(prob_seqx)

backward Probability Table
[[0.077 0.175 0.65  1.   ]
 [0.147 0.25  0.4   1.   ]]

 Probabiliy of sequence=
0.05284999999999999


### FDP 8

In [42]:
#Viterbi algorithm
T=np.array([[0.7,0.3],[0.2,0.8]])
state1H=0.8 
state1T=0.2
state2H=0.3  
state2T=0.7
Sequence='HTTH'
Sequence=np.array(list(Sequence))
s1Prob=np.empty([n])
s2Prob=np.empty([n])
L=len(Sequence)
# Dummy prob array  for fast computation
for i in range(L): 
    if Sequence[i]=='H':
        s1Prob[i]=state1H;
        s2Prob[i]=state2H;
    else:
        s1Prob[i]=state1T;
        s2Prob[i]=state2T; 

ForwardT=np.zeros((2,L));
ForwardT[0,0]=0.5*s1Prob[0];
ForwardT[1,0]=0.5*s2Prob[0];

Ptr=np.zeros((2,L));
Ptr[0,0]=0;
Ptr[1,0]=0;

for j in range(1,L):
    maxval=max([ForwardT[0,j-1]*T[0,0]*s1Prob[j],ForwardT[1,j-1]*T[1,0]*s1Prob[j]]);
    index=[ForwardT[0,j-1]*T[0,0]*s1Prob[j],ForwardT[1,j-1]*T[1,0]*s1Prob[j]].index(maxval)
    ForwardT[0,j]=maxval;
    Ptr[0,j]=index;
    maxval=max([ForwardT[0,j-1]*T[0,1]*s2Prob[j]+ForwardT[1,j-1]*T[1,1]*s2Prob[j]]);
    index=[ForwardT[0,j-1]*T[0,1]*s2Prob[j]+ForwardT[1,j-1]*T[1,1]*s2Prob[j]].index(maxval)
    ForwardT[1,j]=maxval;
    Ptr[1,j]=index;

print('Observed Sequence is')
print(Sequence)
print("\n",'viterbi table is')
print(ForwardT)

# Pathsequence
maxval=max([ForwardT[0,L-1],ForwardT[1,L-1]]);
index=[ForwardT[0,L-1],ForwardT[1,L-1]].index(maxval)
print('prob(sequence along viterbipath)=',maxval)

# Tracking the state sequence include the state 0
patharray=np.zeros(L+1);

# since patharray is one dimensional, single index will do
patharray[L]=index;

for i in reversed(range(0,L)):
    ptrvalue=int(patharray[i+1]);
    patharray[i]=Ptr[ptrvalue,i];

print("\n",'most probable path sequence is')
print(patharray)

Observed Sequence is
['H' 'T' 'T' 'H']

 viterbi table is
[[0.4       0.056     0.00784   0.0169344]
 [0.15      0.168     0.10584   0.0261072]]
prob(sequence along viterbipath)= 0.026107199999999994

 most probable path sequence is
[0. 0. 0. 0. 1.]
